"""Init database tables

Revision ID: 79fb7bcf5ed7
Revises: 
Create Date: 2023-10-03 18:59:58.649506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fb7bcf5ed7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gce_instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resource_type_id', 'gce_instance', ['project_id'], unique=False)
    op.create_table('heartbeat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['gce_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_heartbeat_deadline', 'heartbeat', ['deadline'], unique=False)
    op.create_index('idx_heartbeat_instance_id', 'heartbeat', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_heartbeat_instance_id', table_name='heartbeat')
    op.drop_index('idx_heartbeat_deadline', table_name='heartbeat')
    op.drop_table('heartbeat')
    op.drop_index('idx_resource_type_id', table_name='gce_instance')
    op.drop_table('gce_instance')
    # ### end Alembic commands ###
