# Workflow copied from myself, from an earlier project:
# https://github.com/Afterstone/nettopp-auth-api/tree/develop/.github/workflows

name: Deploy to production

on:
  pull_request:
    branches:
      - develop

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build_and_deploy:
    needs: tests

    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: prod
    secrets: inherit
