name: Tests

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy .env.template to .env
        run: cp .env.template .env

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry==1.6.1
          poetry install

      - name: Run tests
        run: poetry run pytest
